#!/usr/bin/env python3

import argparse
import subprocess
import shlex

__VERSION__ = "v0.1.0"

def flip(command, args, debug=False):
    # Invert the last two arguments
    inverted_args = args[-1:-3:-1] + args[:-2]
    
    # Form the complete command
    full_command = [command] + inverted_args

    # If in debug mode, print the full command
    if debug:
        print("Executing command:", ' '.join(shlex.quote(arg) for arg in full_command))
    
    # Execute the command
    subprocess.run(full_command)

def main():
    # Set up argparse
    parser = argparse.ArgumentParser(description="Flip the last two arguments of a command.")
    parser.add_argument("-d", "--debug", help="Enable debug mode", action="store_true")
    parser.add_argument("command", help="The command to execute")
    parser.add_argument("args", nargs=argparse.REMAINDER, help="The arguments for the command")

    # Parse the arguments
    args = parser.parse_args()

    # Run the flip function
    flip(args.command, args.args, args.debug)

if __name__ == "__main__":
    main()
